package com.LongerDude.LMS.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.Objects;

/**
 * Represents a Book entity in the Library Management System (LMS).
 * This class is mapped to the "books" table in the database.
 */
@Entity
@Table(name = "books")
public class Book {

    /**
     * Unique identifier for the book.
     * This field is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title of the book.
     */
    private String title;

    /**
     * The author of the book.
     */
    private String author;

    /**
     * The current number of copies of this book available in the library.
     */
    private int amount;


    /**
     * Default no-argument constructor required by JPA.
     */
    public Book() {
    }

    /**
     * Constructor for creating a new Book instance before it has an ID assigned by the database.
     *
     * @param title  The title of the book.
     * @param author The author of the book.
     * @param amount The initial stock amount of the book.
     */
    public Book(String title, String author, int amount) {
        this.title = title;
        this.author = author;
        this.amount = amount;
    }

    /**
     * Full constructor including the ID, typically used when retrieving an entity from the database.
     *
     * @param id     The unique identifier of the book.
     * @param title  The title of the book.
     * @param author The author of the book.
     * @param amount The stock amount of the book.
     */
    public Book(Long id, String title, String author, int amount) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.amount = amount;
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public int getAmount() {
        return this.amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    /**
     * Compares this Book object to the specified object.
     * The comparison is based on all fields (id, title, author, amount).
     *
     * @param o The object to compare with.
     * @return true if the objects are equal, false otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Book book = (Book) o;
        return amount == book.amount && Objects.equals(id, book.id) && Objects.equals(title, book.title) && Objects.equals(author, book.author);
    }

    /**
     * Returns a hash code value for the object.
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(id, title, author, amount);
    }

    /**
     * Returns a string representation of the Book object.
     *
     * @return A string containing the title, author, and amount.
     */
    @Override
    public String toString() {
        return this.title + " by " + this.author + ", " + this.amount + " in storage";
    }
}